name: Coverage Upload

on:
  push:
    branches: [master]

jobs:
  upload-coverage:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        
      - name: ✅ Verify coverage file exists
        run: |
          if [ ! -f coverage.xml ]; then
            echo "❌ Error: coverage.xml not found!"
            echo "Please run tests locally with: pytest --cov=orka --cov-report=xml:coverage.xml"
            exit 1
          fi
          echo "✅ Coverage file found"
          
      - name: 📤 Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false
          verbose: true