name: Coverage Upload

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  coverage-upload:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📊 Check for existing coverage file
        run: |
          ls -la
          if [ -f "coverage.xml" ]; then
            echo "Coverage file exists - using committed coverage data"
            ls -la coverage.xml
            head -n 20 coverage.xml
          else
            echo "No coverage.xml file found in repository"
            echo "Please generate coverage locally and commit the coverage.xml file"
            exit 1
          fi

      - name: 📤 Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true
