name: Tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      BASE_OPENAI_MODEL: gpt-4o-mini
      CI: "true" # Standard CI environment variable
      PYTEST_RUNNING: "true" # Set early for all test stages
      SKIP_LLM_TESTS: "true" # Skip LLM tests in CI

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-asyncio coverage

      - name: 🧪 Run domain tests with coverage
        run: |
          # Run the domain tests which are now consolidated
          python -m pytest test/test_domain_*.py --cov=orka --cov-report=xml:coverage.xml --cov-report=term

      - name: 📊 Verify coverage file
        run: |
          ls -la
          if [ -f "coverage.xml" ]; then
            echo "Coverage file exists"
            ls -la coverage.xml
            head -n 20 coverage.xml
          else
            echo "Coverage file does not exist"
            # Generate coverage directly using coverage tool as fallback
            python -m coverage run --source=orka -m pytest test/test_domain_*.py
            python -m coverage xml -o coverage.xml
            python -m coverage report
            ls -la coverage.xml
          fi

      - name: 📤 Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true
